name: "Execute Unit Tests"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-12
    name: "Execute Unit Tests"
    steps:
    - uses: actions/checkout@v3
    - name: "Xcode Select"
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version
    - name: "Generate Project"
      run: swift package generate-xcodeproj
    - name: "iOS16: Unit Tests"
      run: xcodebuild test -project Umbrella.xcodeproj -scheme Umbrella-Package -sdk iphonesimulator16.0 -destination "OS=16.0,name=iPhone 13"
